
tasks:
  - init: chmod a+x mvnw
    command: ./mvnw install -DskipTests=false && ./mvnw spring-boot:run
    
# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
